name: /Users/angelaliu_1/miniconda3/envs/cs329t
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - expat=2.7.1
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.12.12
  - python-dotenv=1.1.1
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - chromadb==1.1.1
      - click==8.3.0
      - coloredlogs==15.0.1
      - distro==1.9.0
      - durationpy==0.10
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fsspec==2025.9.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jiter==0.11.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain==0.3.27
      - langchain-chroma==0.2.6
      - langchain-core==0.3.79
      - langchain-openai==0.3.35
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.37
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - numpy==2.3.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.1
      - openai==2.4.0
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==25.0
      - posthog==5.4.0
      - protobuf==6.33.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.3.0
      - uvicorn==0.37.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - zipp==3.23.0
      - zstandard==0.25.0
